import type { Flow, Run, ApiKey, UserSettings, MonitorAlert, FlowTemplate } from "./types"

export const mockFlows: Flow[] = [
  {
    id: "flow-1",
    name: "Product Price Monitor",
    description: "Track prices across e-commerce sites and alert on drops",
    url: "https://example-store.com/products",
    mode: "monitor",
    status: "active",
    steps: [
      { id: "s1", type: "navigate", label: "Go to product listing" },
      { id: "s2", type: "extract", label: "Extract prices", extractionRules: [
        { field: "name", selector: ".product-title", transform: "text" },
        { field: "price", selector: ".price", transform: "number" },
        { field: "url", selector: ".product-link", attribute: "href", transform: "url" },
      ]},
      { id: "s3", type: "scroll", label: "Scroll to load more" },
      { id: "s4", type: "condition", label: "If next page exists", condition: ".pagination .next", children: [
        { id: "s5", type: "click", label: "Click next page", selector: ".pagination .next" },
      ]},
    ],
    outputSchema: { name: "string", price: "number", url: "string", change: "number" },
    schedule: { expression: "0 */6 * * *", timezone: "America/New_York", enabled: true },
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-03-17T14:30:00Z",
    lastRunAt: "2026-03-18T12:00:00Z",
    successRate: 98.5,
    totalRuns: 248,
    avgDuration: 12400,
  },
  {
    id: "flow-2",
    name: "Job Listings Scraper",
    description: "Extract job postings from multiple job boards",
    url: "https://example-jobs.com/search?q=engineer",
    mode: "extract",
    status: "active",
    steps: [
      { id: "s1", type: "navigate", label: "Search for jobs" },
      { id: "s2", type: "fill", label: "Enter search query", selector: "#search-input", value: "software engineer" },
      { id: "s3", type: "click", label: "Submit search", selector: "#search-btn" },
      { id: "s4", type: "wait", label: "Wait for results" },
      { id: "s5", type: "extract", label: "Extract listings", extractionRules: [
        { field: "title", selector: ".job-title", transform: "text" },
        { field: "company", selector: ".company-name", transform: "text" },
        { field: "location", selector: ".location", transform: "text" },
        { field: "salary", selector: ".salary", transform: "text" },
        { field: "link", selector: ".job-link", attribute: "href", transform: "url" },
      ]},
    ],
    outputSchema: { title: "string", company: "string", location: "string", salary: "string", link: "string" },
    createdAt: "2026-01-20T08:00:00Z",
    updatedAt: "2026-03-16T09:15:00Z",
    lastRunAt: "2026-03-18T06:00:00Z",
    successRate: 96.2,
    totalRuns: 412,
    avgDuration: 28600,
  },
  {
    id: "flow-3",
    name: "Real Estate Auction Monitor",
    description: "Monitor Bid4Assets and county auction sites for new listings",
    url: "https://bid4assets.com/auctions",
    mode: "monitor",
    status: "active",
    steps: [
      { id: "s1", type: "navigate", label: "Go to auction listings" },
      { id: "s2", type: "extract", label: "Extract auctions", extractionRules: [
        { field: "address", selector: ".auction-address", transform: "text" },
        { field: "currentBid", selector: ".current-bid", transform: "number" },
        { field: "endDate", selector: ".end-date", transform: "date" },
        { field: "auctionUrl", selector: ".auction-link", attribute: "href", transform: "url" },
      ]},
    ],
    outputSchema: { address: "string", currentBid: "number", endDate: "string", auctionUrl: "string" },
    schedule: { expression: "0 8 * * *", timezone: "America/New_York", enabled: true },
    createdAt: "2026-02-01T12:00:00Z",
    updatedAt: "2026-03-18T08:00:00Z",
    lastRunAt: "2026-03-18T08:00:00Z",
    successRate: 99.1,
    totalRuns: 45,
    avgDuration: 8200,
  },
  {
    id: "flow-4",
    name: "Contact Form Submitter",
    description: "Automated form submissions for lead outreach",
    url: "https://example-site.com/contact",
    mode: "interact",
    status: "paused",
    steps: [
      { id: "s1", type: "navigate", label: "Go to contact page" },
      { id: "s2", type: "fill", label: "Fill name", selector: "#name", value: "{{name}}" },
      { id: "s3", type: "fill", label: "Fill email", selector: "#email", value: "{{email}}" },
      { id: "s4", type: "fill", label: "Fill message", selector: "#message", value: "{{message}}" },
      { id: "s5", type: "click", label: "Submit form", selector: "#submit-btn" },
      { id: "s6", type: "wait", label: "Wait for confirmation" },
      { id: "s7", type: "extract", label: "Capture confirmation", extractionRules: [
        { field: "confirmationId", selector: ".confirmation-id", transform: "text" },
      ]},
    ],
    outputSchema: { confirmationId: "string", status: "string" },
    createdAt: "2026-03-01T15:00:00Z",
    updatedAt: "2026-03-10T11:00:00Z",
    successRate: 87.3,
    totalRuns: 156,
    avgDuration: 5400,
  },
  {
    id: "flow-5",
    name: "Craigslist Cars Aggregator",
    description: "Aggregate car listings across multiple Craigslist regions",
    url: "https://craigslist.org/search/cta",
    mode: "extract",
    status: "active",
    steps: [
      { id: "s1", type: "navigate", label: "Search cars for sale" },
      { id: "s2", type: "extract", label: "Extract listings", extractionRules: [
        { field: "title", selector: ".result-title", transform: "text" },
        { field: "price", selector: ".result-price", transform: "number" },
        { field: "location", selector: ".result-hood", transform: "text" },
        { field: "link", selector: ".result-title", attribute: "href", transform: "url" },
        { field: "date", selector: ".result-date", attribute: "datetime", transform: "date" },
      ]},
      { id: "s3", type: "loop", label: "Paginate through results", children: [
        { id: "s4", type: "click", label: "Next page", selector: ".next" },
      ]},
    ],
    outputSchema: { title: "string", price: "number", location: "string", link: "string", date: "string" },
    schedule: { expression: "0 */2 * * *", timezone: "America/New_York", enabled: true },
    createdAt: "2026-01-10T09:00:00Z",
    updatedAt: "2026-03-18T10:00:00Z",
    lastRunAt: "2026-03-18T10:00:00Z",
    successRate: 94.7,
    totalRuns: 1024,
    avgDuration: 45200,
  },
  {
    id: "flow-6",
    name: "Social Media Profile Scraper",
    description: "Extract public profile data from social platforms",
    url: "https://example-social.com/profiles",
    mode: "extract",
    status: "draft",
    steps: [
      { id: "s1", type: "navigate", label: "Go to profile page" },
      { id: "s2", type: "wait", label: "Wait for dynamic content" },
      { id: "s3", type: "extract", label: "Extract profile data", extractionRules: [
        { field: "username", selector: ".profile-username", transform: "text" },
        { field: "bio", selector: ".profile-bio", transform: "text" },
        { field: "followers", selector: ".follower-count", transform: "number" },
      ]},
    ],
    outputSchema: { username: "string", bio: "string", followers: "number" },
    createdAt: "2026-03-15T16:00:00Z",
    updatedAt: "2026-03-15T16:00:00Z",
    successRate: 0,
    totalRuns: 0,
    avgDuration: 0,
  },
]

export const mockRuns: Run[] = [
  {
    id: "run-1",
    flowId: "flow-1",
    flowName: "Product Price Monitor",
    status: "completed",
    startedAt: "2026-03-18T12:00:00Z",
    completedAt: "2026-03-18T12:00:12Z",
    duration: 12400,
    itemsExtracted: 147,
    outputPreview: [
      { name: "Wireless Headphones Pro", price: 79.99, url: "/products/headphones", change: -12.5 },
      { name: "USB-C Hub 7-in-1", price: 34.99, url: "/products/hub", change: 0 },
      { name: "Mechanical Keyboard", price: 129.99, url: "/products/keyboard", change: -5.0 },
    ],
    logs: [
      { timestamp: "2026-03-18T12:00:00Z", level: "info", message: "Run started" },
      { timestamp: "2026-03-18T12:00:01Z", level: "info", message: "Navigating to target URL", step: "s1" },
      { timestamp: "2026-03-18T12:00:03Z", level: "info", message: "Page loaded, extracting data", step: "s2" },
      { timestamp: "2026-03-18T12:00:08Z", level: "info", message: "Extracted 147 items across 6 pages", step: "s2" },
      { timestamp: "2026-03-18T12:00:10Z", level: "info", message: "Comparing with previous run data" },
      { timestamp: "2026-03-18T12:00:11Z", level: "info", message: "Found 12 price changes" },
      { timestamp: "2026-03-18T12:00:12Z", level: "info", message: "Run completed successfully" },
    ],
    cost: 0.003,
  },
  {
    id: "run-2",
    flowId: "flow-2",
    flowName: "Job Listings Scraper",
    status: "completed",
    startedAt: "2026-03-18T06:00:00Z",
    completedAt: "2026-03-18T06:00:28Z",
    duration: 28600,
    itemsExtracted: 89,
    outputPreview: [
      { title: "Senior Software Engineer", company: "TechCorp", location: "San Francisco, CA", salary: "$180k-$220k" },
      { title: "Full Stack Developer", company: "StartupXYZ", location: "Remote", salary: "$140k-$170k" },
    ],
    logs: [
      { timestamp: "2026-03-18T06:00:00Z", level: "info", message: "Run started" },
      { timestamp: "2026-03-18T06:00:02Z", level: "info", message: "Navigating to search page", step: "s1" },
      { timestamp: "2026-03-18T06:00:05Z", level: "info", message: "Filling search query", step: "s2" },
      { timestamp: "2026-03-18T06:00:06Z", level: "info", message: "Submitting search", step: "s3" },
      { timestamp: "2026-03-18T06:00:10Z", level: "info", message: "Results loaded", step: "s4" },
      { timestamp: "2026-03-18T06:00:25Z", level: "info", message: "Extracted 89 job listings", step: "s5" },
      { timestamp: "2026-03-18T06:00:28Z", level: "info", message: "Run completed successfully" },
    ],
    cost: 0.008,
  },
  {
    id: "run-3",
    flowId: "flow-5",
    flowName: "Craigslist Cars Aggregator",
    status: "failed",
    startedAt: "2026-03-18T10:00:00Z",
    completedAt: "2026-03-18T10:00:45Z",
    duration: 45000,
    itemsExtracted: 23,
    error: "Rate limited by target site after page 4. Retry scheduled with exponential backoff.",
    logs: [
      { timestamp: "2026-03-18T10:00:00Z", level: "info", message: "Run started" },
      { timestamp: "2026-03-18T10:00:05Z", level: "info", message: "Navigating to search", step: "s1" },
      { timestamp: "2026-03-18T10:00:15Z", level: "info", message: "Extracted page 1-3, 23 items", step: "s2" },
      { timestamp: "2026-03-18T10:00:40Z", level: "warn", message: "HTTP 429 received on page 4", step: "s3" },
      { timestamp: "2026-03-18T10:00:42Z", level: "error", message: "Rate limited. Partial results saved.", step: "s3" },
      { timestamp: "2026-03-18T10:00:45Z", level: "info", message: "Run failed - scheduling retry in 30 minutes" },
    ],
    cost: 0.012,
  },
  {
    id: "run-4",
    flowId: "flow-3",
    flowName: "Real Estate Auction Monitor",
    status: "completed",
    startedAt: "2026-03-18T08:00:00Z",
    completedAt: "2026-03-18T08:00:08Z",
    duration: 8200,
    itemsExtracted: 34,
    outputPreview: [
      { address: "123 Oak St, Austin TX", currentBid: 45000, endDate: "2026-03-25" },
      { address: "456 Elm Ave, Dallas TX", currentBid: 72000, endDate: "2026-03-22" },
    ],
    logs: [
      { timestamp: "2026-03-18T08:00:00Z", level: "info", message: "Run started" },
      { timestamp: "2026-03-18T08:00:02Z", level: "info", message: "Navigating to auctions page", step: "s1" },
      { timestamp: "2026-03-18T08:00:06Z", level: "info", message: "Extracted 34 auction listings", step: "s2" },
      { timestamp: "2026-03-18T08:00:07Z", level: "info", message: "5 new listings detected since last run" },
      { timestamp: "2026-03-18T08:00:08Z", level: "info", message: "Run completed successfully" },
    ],
    cost: 0.002,
  },
  {
    id: "run-5",
    flowId: "flow-1",
    flowName: "Product Price Monitor",
    status: "running",
    startedAt: "2026-03-18T18:00:00Z",
    duration: 0,
    itemsExtracted: 0,
    logs: [
      { timestamp: "2026-03-18T18:00:00Z", level: "info", message: "Run started" },
      { timestamp: "2026-03-18T18:00:01Z", level: "info", message: "Navigating to target URL", step: "s1" },
      { timestamp: "2026-03-18T18:00:03Z", level: "info", message: "Page loaded, beginning extraction", step: "s2" },
    ],
    cost: 0.001,
  },
]

export const mockApiKeys: ApiKey[] = [
  {
    id: "key-1",
    name: "Production API Key",
    key: "scr_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    prefix: "scr_live_",
    createdAt: "2026-01-15T10:00:00Z",
    lastUsedAt: "2026-03-18T17:45:00Z",
    scopes: ["flows:read", "flows:write", "runs:read", "runs:write", "extract:execute"],
  },
  {
    id: "key-2",
    name: "Development Key",
    key: "scr_test_yyyyyyyyyyyyyyyyyyyyyyyyyyyy",
    prefix: "scr_test_",
    createdAt: "2026-02-20T14:00:00Z",
    lastUsedAt: "2026-03-18T12:00:00Z",
    scopes: ["flows:read", "runs:read"],
  },
  {
    id: "key-3",
    name: "CI/CD Pipeline",
    key: "scr_live_zzzzzzzzzzzzzzzzzzzzzzzzzzzz",
    prefix: "scr_live_",
    createdAt: "2026-03-01T09:00:00Z",
    lastUsedAt: "2026-03-18T06:00:00Z",
    scopes: ["flows:read", "runs:read", "runs:write"],
  },
]

export const mockUser: UserSettings = {
  name: "Wyatt",
  email: "wyatt@scraper.dev",
  plan: "professional",
  usage: {
    runsUsed: 1885,
    runsLimit: 5000,
    apiCallsUsed: 12450,
    apiCallsLimit: 50000,
  },
}

export const mockAlerts: MonitorAlert[] = [
  {
    id: "alert-1",
    flowId: "flow-1",
    flowName: "Product Price Monitor",
    type: "change_detected",
    message: "12 price changes detected: 8 decreases, 4 increases. Largest drop: Wireless Headphones Pro (-$11.50)",
    severity: "info",
    createdAt: "2026-03-18T12:00:12Z",
    acknowledged: false,
  },
  {
    id: "alert-2",
    flowId: "flow-5",
    flowName: "Craigslist Cars Aggregator",
    type: "error",
    message: "Run failed due to rate limiting. Auto-retry scheduled in 30 minutes.",
    severity: "warning",
    createdAt: "2026-03-18T10:00:45Z",
    acknowledged: false,
  },
  {
    id: "alert-3",
    flowId: "flow-3",
    flowName: "Real Estate Auction Monitor",
    type: "change_detected",
    message: "5 new auction listings detected in Austin, TX area.",
    severity: "info",
    createdAt: "2026-03-18T08:00:08Z",
    acknowledged: true,
  },
  {
    id: "alert-4",
    flowId: "flow-4",
    flowName: "Contact Form Submitter",
    type: "schedule_missed",
    message: "Flow is paused but has an active schedule. 3 scheduled runs were skipped.",
    severity: "warning",
    createdAt: "2026-03-17T12:00:00Z",
    acknowledged: false,
  },
]

export const mockTemplates: FlowTemplate[] = [
  {
    id: "tmpl-1",
    name: "E-commerce Price Tracker",
    description: "Monitor product prices and get alerts on drops",
    category: "E-commerce",
    mode: "monitor",
    url: "",
    steps: [
      { id: "s1", type: "navigate", label: "Go to product page" },
      { id: "s2", type: "extract", label: "Extract product data" },
    ],
    outputSchema: { name: "string", price: "number", availability: "boolean" },
  },
  {
    id: "tmpl-2",
    name: "Job Board Scraper",
    description: "Extract job listings with title, company, salary, and location",
    category: "Jobs",
    mode: "extract",
    url: "",
    steps: [
      { id: "s1", type: "navigate", label: "Search jobs" },
      { id: "s2", type: "fill", label: "Enter search terms" },
      { id: "s3", type: "extract", label: "Extract listings" },
    ],
    outputSchema: { title: "string", company: "string", salary: "string", location: "string" },
  },
  {
    id: "tmpl-3",
    name: "Real Estate Listings",
    description: "Scrape property listings from real estate sites",
    category: "Real Estate",
    mode: "extract",
    url: "",
    steps: [
      { id: "s1", type: "navigate", label: "Go to listings" },
      { id: "s2", type: "extract", label: "Extract property data" },
    ],
    outputSchema: { address: "string", price: "number", beds: "number", baths: "number", sqft: "number" },
  },
  {
    id: "tmpl-4",
    name: "Form Auto-Filler",
    description: "Automate filling and submitting web forms",
    category: "Automation",
    mode: "interact",
    url: "",
    steps: [
      { id: "s1", type: "navigate", label: "Go to form" },
      { id: "s2", type: "fill", label: "Fill fields" },
      { id: "s3", type: "click", label: "Submit" },
    ],
    outputSchema: { status: "string", confirmationId: "string" },
  },
  {
    id: "tmpl-5",
    name: "News & Article Aggregator",
    description: "Collect articles from news sites with title, author, date",
    category: "Content",
    mode: "extract",
    url: "",
    steps: [
      { id: "s1", type: "navigate", label: "Go to news page" },
      { id: "s2", type: "extract", label: "Extract articles" },
    ],
    outputSchema: { title: "string", author: "string", date: "string", summary: "string", url: "string" },
  },
  {
    id: "tmpl-6",
    name: "Social Media Monitor",
    description: "Track posts and engagement metrics on social platforms",
    category: "Social Media",
    mode: "monitor",
    url: "",
    steps: [
      { id: "s1", type: "navigate", label: "Go to profile/page" },
      { id: "s2", type: "scroll", label: "Load more posts" },
      { id: "s3", type: "extract", label: "Extract post data" },
    ],
    outputSchema: { content: "string", likes: "number", comments: "number", date: "string" },
  },
  {
    id: "tmpl-7",
    name: "Competitor Price Comparison",
    description: "Compare prices across multiple competitor sites",
    category: "E-commerce",
    mode: "extract",
    url: "",
    steps: [
      { id: "s1", type: "navigate", label: "Search for product" },
      { id: "s2", type: "extract", label: "Extract competitor prices" },
    ],
    outputSchema: { site: "string", productName: "string", price: "number", inStock: "boolean" },
  },
  {
    id: "tmpl-8",
    name: "Lead Generation Scraper",
    description: "Extract business contact information from directories",
    category: "Sales",
    mode: "extract",
    url: "",
    steps: [
      { id: "s1", type: "navigate", label: "Go to directory" },
      { id: "s2", type: "fill", label: "Enter search criteria" },
      { id: "s3", type: "extract", label: "Extract contact data" },
    ],
    outputSchema: { business: "string", phone: "string", email: "string", address: "string", website: "string" },
  },
]
