import type { Flow, Run, FlowTemplate } from "./types"

export const mockFlows: Flow[] = [
  {
    id: "flow-1",
    name: "Product Price Monitor",
    description: "Track Amazon product prices for wireless headphones and alert on price drops",
    url: "https://www.amazon.com/s?k=wireless+headphones",
    mode: "monitor",
    status: "active",
    steps: [
      { id: "s1", type: "navigate", label: "Go to Amazon search results" },
      { id: "s2", type: "wait", label: "Wait for product grid to load" },
      { id: "s3", type: "extract", label: "Extract product listings", extractionRules: [
        { field: "name", selector: "h2 a span", transform: "text" },
        { field: "price", selector: ".a-price .a-offscreen", transform: "number" },
        { field: "url", selector: "h2 a", attribute: "href", transform: "url" },
      ]},
      { id: "s4", type: "scroll", label: "Scroll to load more products" },
      { id: "s5", type: "condition", label: "Check for next page", condition: ".s-pagination-next", children: [
        { id: "s6", type: "click", label: "Go to next page", selector: ".s-pagination-next" },
      ]},
    ],
    outputSchema: { name: "string", price: "number", url: "string", change: "number" },
    schedule: { expression: "0 */6 * * *", timezone: "America/New_York", enabled: true },
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-03-17T14:30:00Z",
    lastRunAt: "2026-03-18T12:00:00Z",
    successRate: 98.5,
    totalRuns: 248,
    avgDuration: 12400,
  },
  {
    id: "flow-2",
    name: "Job Listings Scraper",
    description: "Extract software engineer job postings from Indeed with salary and location data",
    url: "https://www.indeed.com/jobs?q=software+engineer&l=remote",
    mode: "extract",
    status: "active",
    steps: [
      { id: "s1", type: "navigate", label: "Go to Indeed search results" },
      { id: "s2", type: "wait", label: "Wait for job cards to load" },
      { id: "s3", type: "extract", label: "Extract job listings", extractionRules: [
        { field: "title", selector: ".jobTitle a span", transform: "text" },
        { field: "company", selector: "[data-testid='company-name']", transform: "text" },
        { field: "location", selector: "[data-testid='text-location']", transform: "text" },
        { field: "salary", selector: ".salary-snippet-container", transform: "text" },
        { field: "link", selector: ".jobTitle a", attribute: "href", transform: "url" },
      ]},
      { id: "s4", type: "condition", label: "Check for next page", condition: "[data-testid='pagination-page-next']", children: [
        { id: "s5", type: "click", label: "Next page", selector: "[data-testid='pagination-page-next']" },
      ]},
    ],
    outputSchema: { title: "string", company: "string", location: "string", salary: "string", link: "string" },
    createdAt: "2026-01-20T08:00:00Z",
    updatedAt: "2026-03-16T09:15:00Z",
    lastRunAt: "2026-03-18T06:00:00Z",
    successRate: 96.2,
    totalRuns: 412,
    avgDuration: 28600,
  },
  {
    id: "flow-3",
    name: "Real Estate Auction Monitor",
    description: "Monitor Zillow Austin listings for new properties and price changes",
    url: "https://www.zillow.com/austin-tx/",
    mode: "monitor",
    status: "active",
    steps: [
      { id: "s1", type: "navigate", label: "Go to Zillow Austin listings" },
      { id: "s2", type: "wait", label: "Wait for property cards to render" },
      { id: "s3", type: "extract", label: "Extract property listings", extractionRules: [
        { field: "address", selector: "[data-test='property-card-addr']", transform: "text" },
        { field: "currentBid", selector: "[data-test='property-card-price']", transform: "number" },
        { field: "endDate", selector: ".list-card-statusText", transform: "text" },
        { field: "auctionUrl", selector: "[data-test='property-card-link']", attribute: "href", transform: "url" },
      ]},
    ],
    outputSchema: { address: "string", currentBid: "number", endDate: "string", auctionUrl: "string" },
    schedule: { expression: "0 8 * * *", timezone: "America/New_York", enabled: true },
    createdAt: "2026-02-01T12:00:00Z",
    updatedAt: "2026-03-18T08:00:00Z",
    lastRunAt: "2026-03-18T08:00:00Z",
    successRate: 99.1,
    totalRuns: 45,
    avgDuration: 8200,
  },
  {
    id: "flow-4",
    name: "Contact Form Submitter",
    description: "Automated HubSpot demo request form submissions for lead outreach",
    url: "https://www.hubspot.com/products/get-started",
    mode: "interact",
    status: "paused",
    steps: [
      { id: "s1", type: "navigate", label: "Go to HubSpot demo request page" },
      { id: "s2", type: "fill", label: "Fill first name", selector: "#firstname-input", value: "{{firstName}}" },
      { id: "s3", type: "fill", label: "Fill last name", selector: "#lastname-input", value: "{{lastName}}" },
      { id: "s4", type: "fill", label: "Fill email", selector: "#email-input", value: "{{email}}" },
      { id: "s5", type: "click", label: "Submit form", selector: "button[type='submit']" },
      { id: "s6", type: "wait", label: "Wait for confirmation" },
      { id: "s7", type: "extract", label: "Capture confirmation", extractionRules: [
        { field: "confirmationId", selector: ".confirmation-message", transform: "text" },
      ]},
    ],
    outputSchema: { confirmationId: "string", status: "string" },
    createdAt: "2026-03-01T15:00:00Z",
    updatedAt: "2026-03-10T11:00:00Z",
    successRate: 87.3,
    totalRuns: 156,
    avgDuration: 5400,
  },
  {
    id: "flow-5",
    name: "Craigslist Cars Aggregator",
    description: "Aggregate car listings from SF Bay Area Craigslist with price and location",
    url: "https://sfbay.craigslist.org/search/cta",
    mode: "extract",
    status: "active",
    steps: [
      { id: "s1", type: "navigate", label: "Go to SF Bay Craigslist cars for sale" },
      { id: "s2", type: "extract", label: "Extract car listings", extractionRules: [
        { field: "title", selector: ".cl-search-result .titlestring", transform: "text" },
        { field: "price", selector: ".cl-search-result .priceinfo", transform: "number" },
        { field: "location", selector: ".cl-search-result .meta", transform: "text" },
        { field: "link", selector: ".cl-search-result a.titlestring", attribute: "href", transform: "url" },
        { field: "date", selector: ".cl-search-result .meta .datetime", attribute: "datetime", transform: "date" },
      ]},
      { id: "s3", type: "loop", label: "Paginate through results", children: [
        { id: "s4", type: "click", label: "Next page", selector: ".cl-next-page" },
      ]},
    ],
    outputSchema: { title: "string", price: "number", location: "string", link: "string", date: "string" },
    schedule: { expression: "0 */2 * * *", timezone: "America/New_York", enabled: true },
    createdAt: "2026-01-10T09:00:00Z",
    updatedAt: "2026-03-18T10:00:00Z",
    lastRunAt: "2026-03-18T10:00:00Z",
    successRate: 94.7,
    totalRuns: 1024,
    avgDuration: 45200,
  },
  {
    id: "flow-6",
    name: "Social Media Profile Scraper",
    description: "Extract public profile data from GitHub trending repositories",
    url: "https://github.com/trending",
    mode: "extract",
    status: "draft",
    steps: [
      { id: "s1", type: "navigate", label: "Go to GitHub trending page" },
      { id: "s2", type: "wait", label: "Wait for trending repos to load" },
      { id: "s3", type: "extract", label: "Extract trending repository data", extractionRules: [
        { field: "username", selector: "h2.h3.lh-condensed a", transform: "text" },
        { field: "bio", selector: "p.col-9", transform: "text" },
        { field: "followers", selector: ".d-inline-block.float-sm-right .Link--muted:first-child", transform: "number" },
      ]},
    ],
    outputSchema: { username: "string", bio: "string", followers: "number" },
    createdAt: "2026-03-15T16:00:00Z",
    updatedAt: "2026-03-15T16:00:00Z",
    successRate: 0,
    totalRuns: 0,
    avgDuration: 0,
  },
]

export const mockRuns: Run[] = [
  {
    id: "run-1",
    flowId: "flow-1",
    flowName: "Product Price Monitor",
    status: "completed",
    startedAt: "2026-03-18T12:00:00Z",
    completedAt: "2026-03-18T12:00:12Z",
    duration: 12400,
    itemsExtracted: 147,
    outputPreview: [
      { name: "Sony WH-1000XM5 Wireless Headphones", price: 278.00, url: "/dp/B09XS7JWHH", change: -20.00 },
      { name: "Apple AirPods Pro (2nd Gen)", price: 189.99, url: "/dp/B0D1XD1ZV3", change: -9.01 },
      { name: "Bose QuietComfort Ultra Headphones", price: 349.00, url: "/dp/B0CCZ26B5V", change: 0 },
    ],
    logs: [
      { timestamp: "2026-03-18T12:00:00Z", level: "info", message: "Run started" },
      { timestamp: "2026-03-18T12:00:01Z", level: "info", message: "Navigating to target URL", step: "s1" },
      { timestamp: "2026-03-18T12:00:03Z", level: "info", message: "Page loaded, extracting data", step: "s2" },
      { timestamp: "2026-03-18T12:00:08Z", level: "info", message: "Extracted 147 items across 6 pages", step: "s2" },
      { timestamp: "2026-03-18T12:00:10Z", level: "info", message: "Comparing with previous run data" },
      { timestamp: "2026-03-18T12:00:11Z", level: "info", message: "Found 12 price changes" },
      { timestamp: "2026-03-18T12:00:12Z", level: "info", message: "Run completed successfully" },
    ],
    cost: 0.003,
  },
  {
    id: "run-2",
    flowId: "flow-2",
    flowName: "Job Listings Scraper",
    status: "completed",
    startedAt: "2026-03-18T06:00:00Z",
    completedAt: "2026-03-18T06:00:28Z",
    duration: 28600,
    itemsExtracted: 89,
    outputPreview: [
      { title: "Senior Software Engineer", company: "Google", location: "Mountain View, CA", salary: "$180,000 - $260,000 a year" },
      { title: "Full Stack Developer", company: "Stripe", location: "Remote", salary: "$150,000 - $200,000 a year" },
    ],
    logs: [
      { timestamp: "2026-03-18T06:00:00Z", level: "info", message: "Run started" },
      { timestamp: "2026-03-18T06:00:02Z", level: "info", message: "Navigating to search page", step: "s1" },
      { timestamp: "2026-03-18T06:00:05Z", level: "info", message: "Filling search query", step: "s2" },
      { timestamp: "2026-03-18T06:00:06Z", level: "info", message: "Submitting search", step: "s3" },
      { timestamp: "2026-03-18T06:00:10Z", level: "info", message: "Results loaded", step: "s4" },
      { timestamp: "2026-03-18T06:00:25Z", level: "info", message: "Extracted 89 job listings", step: "s5" },
      { timestamp: "2026-03-18T06:00:28Z", level: "info", message: "Run completed successfully" },
    ],
    cost: 0.008,
  },
  {
    id: "run-3",
    flowId: "flow-5",
    flowName: "Craigslist Cars Aggregator",
    status: "failed",
    startedAt: "2026-03-18T10:00:00Z",
    completedAt: "2026-03-18T10:00:45Z",
    duration: 45000,
    itemsExtracted: 23,
    error: "Rate limited by target site after page 4. Retry scheduled with exponential backoff.",
    logs: [
      { timestamp: "2026-03-18T10:00:00Z", level: "info", message: "Run started" },
      { timestamp: "2026-03-18T10:00:05Z", level: "info", message: "Navigating to search", step: "s1" },
      { timestamp: "2026-03-18T10:00:15Z", level: "info", message: "Extracted page 1-3, 23 items", step: "s2" },
      { timestamp: "2026-03-18T10:00:40Z", level: "warn", message: "HTTP 429 received on page 4", step: "s3" },
      { timestamp: "2026-03-18T10:00:42Z", level: "error", message: "Rate limited. Partial results saved.", step: "s3" },
      { timestamp: "2026-03-18T10:00:45Z", level: "info", message: "Run failed - scheduling retry in 30 minutes" },
    ],
    cost: 0.012,
  },
  {
    id: "run-4",
    flowId: "flow-3",
    flowName: "Real Estate Auction Monitor",
    status: "completed",
    startedAt: "2026-03-18T08:00:00Z",
    completedAt: "2026-03-18T08:00:08Z",
    duration: 8200,
    itemsExtracted: 34,
    outputPreview: [
      { address: "1204 E Cesar Chavez St, Austin, TX 78702", currentBid: 525000, endDate: "2026-03-25" },
      { address: "3814 Arrow Dr, Austin, TX 78749", currentBid: 389000, endDate: "2026-03-22" },
    ],
    logs: [
      { timestamp: "2026-03-18T08:00:00Z", level: "info", message: "Run started" },
      { timestamp: "2026-03-18T08:00:02Z", level: "info", message: "Navigating to auctions page", step: "s1" },
      { timestamp: "2026-03-18T08:00:06Z", level: "info", message: "Extracted 34 auction listings", step: "s2" },
      { timestamp: "2026-03-18T08:00:07Z", level: "info", message: "5 new listings detected since last run" },
      { timestamp: "2026-03-18T08:00:08Z", level: "info", message: "Run completed successfully" },
    ],
    cost: 0.002,
  },
  {
    id: "run-5",
    flowId: "flow-1",
    flowName: "Product Price Monitor",
    status: "running",
    startedAt: "2026-03-18T18:00:00Z",
    duration: 0,
    itemsExtracted: 0,
    logs: [
      { timestamp: "2026-03-18T18:00:00Z", level: "info", message: "Run started" },
      { timestamp: "2026-03-18T18:00:01Z", level: "info", message: "Navigating to target URL", step: "s1" },
      { timestamp: "2026-03-18T18:00:03Z", level: "info", message: "Page loaded, beginning extraction", step: "s2" },
    ],
    cost: 0.001,
  },
]

export const mockTemplates: FlowTemplate[] = [
  {
    id: "tmpl-amazon-products",
    name: "Amazon Product Scraper",
    description: "Extract product listings from Amazon search results including title, price, rating, review count, and product URL",
    category: "E-commerce",
    mode: "extract",
    url: "https://www.amazon.com/s?k=wireless+headphones",
    steps: [
      { id: "s1", type: "navigate", label: "Go to Amazon search results" },
      { id: "s2", type: "wait", label: "Wait for product grid to load" },
      { id: "s3", type: "extract", label: "Extract product listings", extractionRules: [
        { field: "title", selector: "h2 a span", transform: "text" },
        { field: "price", selector: ".a-price .a-offscreen", transform: "text" },
        { field: "rating", selector: ".a-icon-alt", transform: "text" },
        { field: "reviewCount", selector: ".a-size-base.s-underline-text", transform: "text" },
        { field: "url", selector: "h2 a", attribute: "href", transform: "url" },
        { field: "image", selector: ".s-image", attribute: "src", transform: "url" },
      ]},
      { id: "s4", type: "scroll", label: "Scroll to load more products" },
      { id: "s5", type: "condition", label: "Check for next page", condition: ".s-pagination-next", children: [
        { id: "s6", type: "click", label: "Go to next page", selector: ".s-pagination-next" },
      ]},
    ],
    outputSchema: { title: "string", price: "string", rating: "string", reviewCount: "string", url: "string", image: "string" },
  },
  {
    id: "tmpl-ebay-listings",
    name: "eBay Listings Scraper",
    description: "Extract auction and buy-it-now listings from eBay search results with prices, shipping, seller info, and time remaining",
    category: "E-commerce",
    mode: "extract",
    url: "https://www.ebay.com/sch/i.html?_nkw=vintage+watches",
    steps: [
      { id: "s1", type: "navigate", label: "Go to eBay search results" },
      { id: "s2", type: "extract", label: "Extract listings", extractionRules: [
        { field: "title", selector: ".s-item__title span", transform: "text" },
        { field: "price", selector: ".s-item__price", transform: "text" },
        { field: "shipping", selector: ".s-item__shipping", transform: "text" },
        { field: "condition", selector: ".SECONDARY_INFO", transform: "text" },
        { field: "url", selector: ".s-item__link", attribute: "href", transform: "url" },
        { field: "image", selector: ".s-item__image-img", attribute: "src", transform: "url" },
      ]},
    ],
    outputSchema: { title: "string", price: "string", shipping: "string", condition: "string", url: "string", image: "string" },
  },
  {
    id: "tmpl-linkedin-jobs",
    name: "LinkedIn Job Listings",
    description: "Extract job postings from LinkedIn Jobs including title, company, location, salary range, and posting date",
    category: "Jobs",
    mode: "extract",
    url: "https://www.linkedin.com/jobs/search/?keywords=software+engineer",
    steps: [
      { id: "s1", type: "navigate", label: "Go to LinkedIn job search" },
      { id: "s2", type: "scroll", label: "Scroll to load job cards" },
      { id: "s3", type: "extract", label: "Extract job listings", extractionRules: [
        { field: "title", selector: ".base-search-card__title", transform: "text" },
        { field: "company", selector: ".base-search-card__subtitle", transform: "text" },
        { field: "location", selector: ".job-search-card__location", transform: "text" },
        { field: "date", selector: ".job-search-card__listdate", attribute: "datetime", transform: "date" },
        { field: "url", selector: ".base-card__full-link", attribute: "href", transform: "url" },
      ]},
    ],
    outputSchema: { title: "string", company: "string", location: "string", date: "string", url: "string" },
  },
  {
    id: "tmpl-indeed-jobs",
    name: "Indeed Job Scraper",
    description: "Extract job listings from Indeed with title, company, salary, location, and job description snippet",
    category: "Jobs",
    mode: "extract",
    url: "https://www.indeed.com/jobs?q=data+analyst&l=remote",
    steps: [
      { id: "s1", type: "navigate", label: "Go to Indeed search results" },
      { id: "s2", type: "extract", label: "Extract job cards", extractionRules: [
        { field: "title", selector: ".jobTitle a span", transform: "text" },
        { field: "company", selector: "[data-testid='company-name']", transform: "text" },
        { field: "location", selector: "[data-testid='text-location']", transform: "text" },
        { field: "salary", selector: ".salary-snippet-container", transform: "text" },
        { field: "snippet", selector: ".job-snippet", transform: "text" },
        { field: "url", selector: ".jobTitle a", attribute: "href", transform: "url" },
      ]},
      { id: "s3", type: "condition", label: "Check for next page", condition: "[data-testid='pagination-page-next']", children: [
        { id: "s4", type: "click", label: "Next page", selector: "[data-testid='pagination-page-next']" },
      ]},
    ],
    outputSchema: { title: "string", company: "string", location: "string", salary: "string", snippet: "string", url: "string" },
  },
  {
    id: "tmpl-zillow-listings",
    name: "Zillow Property Listings",
    description: "Extract real estate listings from Zillow including address, price, beds, baths, square footage, and listing URL",
    category: "Real Estate",
    mode: "extract",
    url: "https://www.zillow.com/austin-tx/",
    steps: [
      { id: "s1", type: "navigate", label: "Go to Zillow search results" },
      { id: "s2", type: "wait", label: "Wait for listings to render" },
      { id: "s3", type: "extract", label: "Extract property cards", extractionRules: [
        { field: "address", selector: "[data-test='property-card-addr']", transform: "text" },
        { field: "price", selector: "[data-test='property-card-price']", transform: "text" },
        { field: "beds", selector: "ul.StyledPropertyCardHomeDetailsList-c11n-8-84-3__sc-1xvdaej-0 li:nth-child(1) b", transform: "text" },
        { field: "baths", selector: "ul.StyledPropertyCardHomeDetailsList-c11n-8-84-3__sc-1xvdaej-0 li:nth-child(2) b", transform: "text" },
        { field: "sqft", selector: "ul.StyledPropertyCardHomeDetailsList-c11n-8-84-3__sc-1xvdaej-0 li:nth-child(3) b", transform: "text" },
        { field: "url", selector: "[data-test='property-card-link']", attribute: "href", transform: "url" },
      ]},
    ],
    outputSchema: { address: "string", price: "string", beds: "string", baths: "string", sqft: "string", url: "string" },
  },
  {
    id: "tmpl-hackernews",
    name: "Hacker News Top Stories",
    description: "Extract top stories from Hacker News with title, URL, points, author, comment count, and submission time",
    category: "Content",
    mode: "extract",
    url: "https://news.ycombinator.com/",
    steps: [
      { id: "s1", type: "navigate", label: "Go to Hacker News front page" },
      { id: "s2", type: "extract", label: "Extract stories", extractionRules: [
        { field: "title", selector: ".titleline a", transform: "text" },
        { field: "url", selector: ".titleline a", attribute: "href", transform: "url" },
        { field: "points", selector: ".score", transform: "text" },
        { field: "author", selector: ".hnuser", transform: "text" },
        { field: "commentCount", selector: ".subline a:last-child", transform: "text" },
        { field: "age", selector: ".age", transform: "text" },
      ]},
    ],
    outputSchema: { title: "string", url: "string", points: "string", author: "string", commentCount: "string", age: "string" },
  },
  {
    id: "tmpl-github-trending",
    name: "GitHub Trending Repositories",
    description: "Extract trending repositories from GitHub including repo name, description, language, stars, and forks",
    category: "Content",
    mode: "extract",
    url: "https://github.com/trending",
    steps: [
      { id: "s1", type: "navigate", label: "Go to GitHub trending page" },
      { id: "s2", type: "wait", label: "Wait for repository list to load" },
      { id: "s3", type: "extract", label: "Extract trending repos", extractionRules: [
        { field: "name", selector: "h2.h3.lh-condensed a", transform: "text" },
        { field: "description", selector: "p.col-9.color-fg-muted", transform: "text" },
        { field: "language", selector: "[itemprop='programmingLanguage']", transform: "text" },
        { field: "starsToday", selector: ".d-inline-block.float-sm-right", transform: "text" },
        { field: "totalStars", selector: ".Link--muted.d-inline-block.mr-3:nth-child(1)", transform: "text" },
        { field: "forks", selector: ".Link--muted.d-inline-block.mr-3:nth-child(2)", transform: "text" },
        { field: "url", selector: "h2.h3.lh-condensed a", attribute: "href", transform: "url" },
      ]},
    ],
    outputSchema: { name: "string", description: "string", language: "string", starsToday: "string", totalStars: "string", forks: "string", url: "string" },
  },
  {
    id: "tmpl-reddit-posts",
    name: "Reddit Subreddit Posts",
    description: "Extract posts from a Reddit subreddit including title, score, author, comment count, and submission time",
    category: "Social Media",
    mode: "extract",
    url: "https://old.reddit.com/r/technology/",
    steps: [
      { id: "s1", type: "navigate", label: "Go to subreddit page" },
      { id: "s2", type: "extract", label: "Extract posts", extractionRules: [
        { field: "title", selector: ".thing .title a.title", transform: "text" },
        { field: "score", selector: ".thing .score.unvoted", transform: "text" },
        { field: "author", selector: ".thing .author", transform: "text" },
        { field: "commentCount", selector: ".thing .comments", transform: "text" },
        { field: "url", selector: ".thing .title a.title", attribute: "href", transform: "url" },
        { field: "timePosted", selector: ".thing time", attribute: "datetime", transform: "date" },
      ]},
    ],
    outputSchema: { title: "string", score: "string", author: "string", commentCount: "string", url: "string", timePosted: "string" },
  },
  {
    id: "tmpl-craigslist-cars",
    name: "Craigslist Car Listings",
    description: "Extract car listings from Craigslist with title, price, location, URL, and posting date",
    category: "E-commerce",
    mode: "extract",
    url: "https://sfbay.craigslist.org/search/cta",
    steps: [
      { id: "s1", type: "navigate", label: "Go to Craigslist cars for sale" },
      { id: "s2", type: "extract", label: "Extract car listings", extractionRules: [
        { field: "title", selector: ".cl-search-result .titlestring", transform: "text" },
        { field: "price", selector: ".cl-search-result .priceinfo", transform: "text" },
        { field: "location", selector: ".cl-search-result .meta", transform: "text" },
        { field: "url", selector: ".cl-search-result a.titlestring", attribute: "href", transform: "url" },
        { field: "datePosted", selector: ".cl-search-result .meta .datetime", attribute: "datetime", transform: "date" },
      ]},
      { id: "s3", type: "condition", label: "Check for next page", condition: ".cl-next-page", children: [
        { id: "s4", type: "click", label: "Go to next page", selector: ".cl-next-page" },
      ]},
    ],
    outputSchema: { title: "string", price: "string", location: "string", url: "string", datePosted: "string" },
  },
  {
    id: "tmpl-google-maps-businesses",
    name: "Google Maps Business Scraper",
    description: "Extract business listings from Google Maps including name, rating, review count, address, phone, and website",
    category: "Sales",
    mode: "extract",
    url: "https://www.google.com/maps/search/restaurants+near+me",
    steps: [
      { id: "s1", type: "navigate", label: "Go to Google Maps search results" },
      { id: "s2", type: "wait", label: "Wait for business listings to load" },
      { id: "s3", type: "scroll", label: "Scroll results panel to load more" },
      { id: "s4", type: "extract", label: "Extract business listings", extractionRules: [
        { field: "name", selector: ".fontHeadlineSmall", transform: "text" },
        { field: "rating", selector: ".MW4etd", transform: "text" },
        { field: "reviewCount", selector: ".UY7F9", transform: "text" },
        { field: "address", selector: ".W4Efsd:nth-child(1) .W4Efsd:nth-child(2) span:nth-child(2)", transform: "text" },
        { field: "phone", selector: ".W4Efsd:nth-child(2) .W4Efsd span:nth-child(2)", transform: "text" },
        { field: "website", selector: "a.lcr4fd", attribute: "href", transform: "url" },
      ]},
    ],
    outputSchema: { name: "string", rating: "string", reviewCount: "string", address: "string", phone: "string", website: "string" },
  },
  {
    id: "tmpl-twitter-profile",
    name: "X (Twitter) Profile Scraper",
    description: "Extract public profile data from X/Twitter including display name, handle, bio, follower count, and tweet count",
    category: "Social Media",
    mode: "extract",
    url: "https://x.com/elonmusk",
    steps: [
      { id: "s1", type: "navigate", label: "Go to X profile page" },
      { id: "s2", type: "wait", label: "Wait for profile data to load" },
      { id: "s3", type: "extract", label: "Extract profile data", extractionRules: [
        { field: "displayName", selector: "[data-testid='UserName'] span:first-child", transform: "text" },
        { field: "handle", selector: "[data-testid='UserName'] div:nth-child(2) span", transform: "text" },
        { field: "bio", selector: "[data-testid='UserDescription']", transform: "text" },
        { field: "followerCount", selector: "a[href$='/verified_followers'] span span", transform: "text" },
        { field: "followingCount", selector: "a[href$='/following'] span span", transform: "text" },
        { field: "tweetCount", selector: "[data-testid='UserName'] + div", transform: "text" },
      ]},
    ],
    outputSchema: { displayName: "string", handle: "string", bio: "string", followerCount: "string", followingCount: "string", tweetCount: "string" },
  },
  {
    id: "tmpl-producthunt-daily",
    name: "Product Hunt Daily",
    description: "Extract daily product launches from Product Hunt with product name, tagline, upvotes, and maker info",
    category: "Content",
    mode: "extract",
    url: "https://www.producthunt.com/",
    steps: [
      { id: "s1", type: "navigate", label: "Go to Product Hunt homepage" },
      { id: "s2", type: "wait", label: "Wait for product cards to load" },
      { id: "s3", type: "extract", label: "Extract daily products", extractionRules: [
        { field: "name", selector: "[data-test='product-item-name']", transform: "text" },
        { field: "tagline", selector: "[data-test='product-item-tagline']", transform: "text" },
        { field: "upvotes", selector: "[data-test='vote-button'] span", transform: "text" },
        { field: "maker", selector: "[data-test='product-item-meta'] a", transform: "text" },
        { field: "url", selector: "[data-test='product-item-name']", attribute: "href", transform: "url" },
        { field: "category", selector: "[data-test='product-item-category']", transform: "text" },
      ]},
    ],
    outputSchema: { name: "string", tagline: "string", upvotes: "string", maker: "string", url: "string", category: "string" },
  },
]

export const templateExampleData: Record<string, Record<string, string>[]> = {
  "tmpl-amazon-products": [
    { title: "Sony WH-1000XM5 Wireless Headphones", price: "$278.00", rating: "4.6 out of 5 stars", reviewCount: "12,847", url: "/dp/B09XS7JWHH", image: "https://m.media-amazon.com/images/I/51aYfkJTb-L.jpg" },
    { title: "Apple AirPods Pro (2nd Generation)", price: "$189.99", rating: "4.7 out of 5 stars", reviewCount: "98,231", url: "/dp/B0BDHWDR12", image: "https://m.media-amazon.com/images/I/61SUj2a-hEL.jpg" },
    { title: "Bose QuietComfort Ultra Headphones", price: "$349.00", rating: "4.5 out of 5 stars", reviewCount: "8,439", url: "/dp/B0CCZ26B5V", image: "https://m.media-amazon.com/images/I/51QcNxJMt8L.jpg" },
  ],
  "tmpl-ebay-listings": [
    { title: "Vintage Omega Seamaster Automatic 1960s", price: "$1,299.00", shipping: "Free shipping", condition: "Pre-Owned", url: "/itm/295712834", image: "https://i.ebayimg.com/images/g/example1.jpg" },
    { title: "Rolex Datejust 36mm 1978 Gold/Steel", price: "$4,850.00", shipping: "+$14.95 shipping", condition: "Pre-Owned", url: "/itm/295819234", image: "https://i.ebayimg.com/images/g/example2.jpg" },
    { title: "Seiko 5 Sports Automatic SRPD73K1", price: "$185.50", shipping: "Free shipping", condition: "New with tags", url: "/itm/295623412", image: "https://i.ebayimg.com/images/g/example3.jpg" },
  ],
  "tmpl-linkedin-jobs": [
    { title: "Senior Software Engineer", company: "Google", location: "Mountain View, CA (Hybrid)", date: "2026-03-17", url: "/jobs/view/3847291" },
    { title: "Full Stack Developer", company: "Stripe", location: "San Francisco, CA (Remote)", date: "2026-03-16", url: "/jobs/view/3851023" },
    { title: "Staff Backend Engineer", company: "Netflix", location: "Los Gatos, CA", date: "2026-03-15", url: "/jobs/view/3849102" },
  ],
  "tmpl-indeed-jobs": [
    { title: "Data Analyst", company: "Meta", location: "Remote", salary: "$95,000 - $135,000/yr", snippet: "Analyze large-scale datasets to drive product decisions...", url: "/viewjob?jk=abc123" },
    { title: "Senior Data Analyst", company: "Shopify", location: "Remote", salary: "$120,000 - $165,000/yr", snippet: "Build dashboards and reporting pipelines for merchant analytics...", url: "/viewjob?jk=def456" },
    { title: "Business Intelligence Analyst", company: "Salesforce", location: "San Francisco, CA", salary: "$105,000 - $145,000/yr", snippet: "Support GTM strategy with data-driven insights and forecasting...", url: "/viewjob?jk=ghi789" },
  ],
  "tmpl-zillow-listings": [
    { address: "4521 Spicewood Springs Rd, Austin, TX 78759", price: "$485,000", beds: "3", baths: "2", sqft: "1,847", url: "/homedetails/4521-Spicewood-Springs-Rd" },
    { address: "2308 Barton Creek Blvd, Austin, TX 78735", price: "$1,250,000", beds: "5", baths: "4", sqft: "3,642", url: "/homedetails/2308-Barton-Creek-Blvd" },
    { address: "910 W Mary St, Austin, TX 78704", price: "$399,900", beds: "2", baths: "1", sqft: "1,120", url: "/homedetails/910-W-Mary-St" },
  ],
  "tmpl-hackernews": [
    { title: "Show HN: Open-source browser automation framework", url: "https://github.com/example/browser-auto", points: "342 points", author: "devbuilder", commentCount: "127 comments", age: "3 hours ago" },
    { title: "PostgreSQL 17 Released with Major Performance Improvements", url: "https://postgresql.org/about/news/17", points: "891 points", author: "pgfan", commentCount: "284 comments", age: "5 hours ago" },
    { title: "Why We Moved from Kubernetes to Bare Metal", url: "https://blog.techstartup.io/bare-metal", points: "567 points", author: "infraeng", commentCount: "203 comments", age: "7 hours ago" },
  ],
  "tmpl-github-trending": [
    { name: "vercel / next.js", description: "The React Framework for the Web", language: "TypeScript", starsToday: "128 stars today", totalStars: "128,400", forks: "27,100", url: "/vercel/next.js" },
    { name: "denoland / deno", description: "A modern runtime for JavaScript and TypeScript", language: "Rust", starsToday: "95 stars today", totalStars: "98,200", forks: "5,400", url: "/denoland/deno" },
    { name: "anthropics / claude-code", description: "Claude Code CLI agent for software development", language: "TypeScript", starsToday: "312 stars today", totalStars: "24,700", forks: "1,800", url: "/anthropics/claude-code" },
  ],
  "tmpl-reddit-posts": [
    { title: "Apple announces M4 Ultra chip for Mac Pro", score: "12.4k", author: "tech_insider", commentCount: "1,847 comments", url: "/r/technology/comments/abc123", timePosted: "2026-03-18T10:30:00Z" },
    { title: "EU passes new right-to-repair legislation", score: "8.7k", author: "euro_news_bot", commentCount: "923 comments", url: "/r/technology/comments/def456", timePosted: "2026-03-18T08:15:00Z" },
    { title: "Starlink now available in 80+ countries", score: "6.2k", author: "space_watcher", commentCount: "1,204 comments", url: "/r/technology/comments/ghi789", timePosted: "2026-03-17T22:00:00Z" },
  ],
  "tmpl-craigslist-cars": [
    { title: "2019 Toyota Camry SE - Clean Title, Low Miles", price: "$18,500", location: "San Mateo", url: "/sfc/cta/d/2019-toyota-camry", datePosted: "2026-03-18" },
    { title: "2021 Honda Civic Sport - 32k Miles", price: "$22,900", location: "Oakland", url: "/eby/cta/d/2021-honda-civic", datePosted: "2026-03-17" },
    { title: "2017 BMW 330i - M Sport Package", price: "$19,800", location: "San Jose", url: "/sby/cta/d/2017-bmw-330i", datePosted: "2026-03-17" },
  ],
  "tmpl-google-maps-businesses": [
    { name: "Joe's Pizza", rating: "4.5", reviewCount: "1,247 reviews", address: "7 Carmine St, New York, NY 10014", phone: "(212) 366-1182", website: "https://joespizzanyc.com" },
    { name: "Shake Shack - Madison Square Park", rating: "4.3", reviewCount: "8,921 reviews", address: "11 Madison Ave, New York, NY 10010", phone: "(212) 889-6600", website: "https://shakeshack.com" },
    { name: "Katz's Delicatessen", rating: "4.4", reviewCount: "15,432 reviews", address: "205 E Houston St, New York, NY 10002", phone: "(212) 254-2246", website: "https://katzsdelicatessen.com" },
  ],
  "tmpl-twitter-profile": [
    { displayName: "Elon Musk", handle: "@elonmusk", bio: "Mars & Cars, Chips & Dips", followerCount: "195.2M", followingCount: "812", tweetCount: "42.1K posts" },
    { displayName: "Sam Altman", handle: "@sama", bio: "CEO of OpenAI", followerCount: "3.8M", followingCount: "1,247", tweetCount: "8.9K posts" },
    { displayName: "Dario Amodei", handle: "@DarioAmodei", bio: "CEO of Anthropic", followerCount: "482K", followingCount: "318", tweetCount: "1.2K posts" },
  ],
  "tmpl-producthunt-daily": [
    { name: "ScrapeFlow", tagline: "Visual web scraping for everyone", upvotes: "847", maker: "@scraperbot", url: "/posts/scrapeflow", category: "Developer Tools" },
    { name: "AIMailer", tagline: "AI-powered cold email campaigns", upvotes: "623", maker: "@emailwhiz", url: "/posts/aimailer", category: "Marketing" },
    { name: "PixelPerfect", tagline: "Design-to-code in one click", upvotes: "1,204", maker: "@pixeldev", url: "/posts/pixelperfect", category: "Design Tools" },
  ],
}

export const templateRatings: Record<string, number> = {
  "tmpl-amazon-products": 4.8,
  "tmpl-ebay-listings": 4.6,
  "tmpl-linkedin-jobs": 4.7,
  "tmpl-indeed-jobs": 4.7,
  "tmpl-zillow-listings": 4.9,
  "tmpl-hackernews": 4.8,
  "tmpl-github-trending": 4.9,
  "tmpl-reddit-posts": 4.5,
  "tmpl-craigslist-cars": 4.6,
  "tmpl-google-maps-businesses": 4.9,
  "tmpl-twitter-profile": 4.5,
  "tmpl-producthunt-daily": 4.7,
}

export const templateUseCounts: Record<string, number> = {
  "tmpl-amazon-products": 3200,
  "tmpl-ebay-listings": 1800,
  "tmpl-linkedin-jobs": 2800,
  "tmpl-indeed-jobs": 2100,
  "tmpl-zillow-listings": 2400,
  "tmpl-hackernews": 1900,
  "tmpl-github-trending": 2600,
  "tmpl-reddit-posts": 1500,
  "tmpl-craigslist-cars": 1700,
  "tmpl-google-maps-businesses": 3100,
  "tmpl-twitter-profile": 1400,
  "tmpl-producthunt-daily": 1600,
}
